<?php
// Cohorts are groups of students assigned specific courses or lessons...
// Cohorts are a post type... inside will be gutenberg blocks that will let you construct a lesson plan per week. You can update it weekly if you like. More importantly you can assign the students you want to this cohort. You could assign courses in total and then potentially assign a lesson per week or per day?
// Would need to figure out grading...
// .... when a "teacher" user role previews a cohort they will see both a teacher view but also a student view what it will look like to them. On their dashboard for this cohort they would see all the students assigned and their progress.
